# Generated by Django 3.2.5 on 2021-07-27 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentFirstName', models.CharField(max_length=100)),
                ('studentLastName', models.CharField(max_length=100)),
                ('studentLevel', models.CharField(max_length=100)),
                ('studentEcode', models.CharField(default='EH174012', max_length=100)),
                ('studentAge', models.IntegerField()),
                ('dateOfJoining', models.DateField(default=datetime.date.today)),
                ('studentPhotoName', models.CharField(max_length=100)),
            ],
        ),
    ]
